description = "A Java ARM64 Builder"

[[buildpacks]]
  id = "paketo-buildpacks/ca-certificates"
  uri = "docker://docker.io/paketo-buildpacks/ca-certificates:3.0.2"

[[buildpacks]]
  id = "paketo-buildpacks/bellsoft-liberica"
  uri = "docker://docker.io/paketo-buildpacks/bellsoft-liberica:9.0.2"

[[buildpacks]]
  id = "paketo-buildpacks/syft"
  uri = "docker://docker.io/paketo-buildpacks/syft:1.3.1"

[[buildpacks]]
  id = "paketo-buildpacks/executable-jar"
  uri = "docker://docker.io/paketo-buildpacks/executable-jar:6.0.2"

[[buildpacks]]
  id = "paketo-buildpacks/spring-boot"
  uri = "docker://docker.io/paketo-buildpacks/spring-boot:5.3.0"

[lifecycle]
  uri = "https://github.com/buildpacks/lifecycle/releases/download/v0.13.2/lifecycle-v0.13.2+linux.arm64.tgz"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/bellsoft-liberica"

  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    optional = true

[stack]
  build-image = "docker.io/dmikusa2pivotal/stack-build:focal"
  id = "com.mikusa.stacks.focal"
  run-image = "docker.io/dmikusa2pivotal/stack-run:focal"
